# NumPy Упражнения

Теперь, когда мы узнали о NumPy, давайте проверим ваши знания. Мы начнем с нескольких простых задач, а затем вам будут заданы более сложные вопросы.

#### Импорт NumPy как np

In [1]:
%pip install numpy

import numpy as np

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


#### Создание массива из 10 нулей

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Создайте массив из 10 единиц

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Создайте массив из 10 пятерок

In [24]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Создадим массив целых чисел от 10 до 50

In [12]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Создадим массив из всех четных целых чисел от 10 до 50

In [11]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Создание матрицы 3x3 со значениями в диапазоне от 0 до 8¶

In [10]:
np.arange(9).reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Создание единичной матрицы 3x3

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Используйте NumPy для генерации случайного числа от 0 до 1

In [30]:
np.random.sample()

0.6060012814062348

#### Используйте NumPy для создания массива из 25 случайных чисел, отобранных из стандартного нормального распределения

In [23]:
np.random.normal(size=25)

array([-0.60931606, -1.83381153,  1.79904542, -0.5395953 , -1.00351901,
        1.19876976,  0.1794753 , -0.15909106,  0.22583895, -0.62535098,
       -1.25545528,  0.29780707, -0.33460229, -0.04649488,  0.54328463,
       -2.8900585 , -0.53980192,  0.27606559,  1.3377189 , -0.07301427,
        0.46137334, -1.18230539, -2.32441919, -1.66502833, -0.83632451])

#### Создайте матрицу 10 на 10 из равномерно удаленных точек от 0.1 до 1( см linspace):

In [25]:
np.linspace(0.1, 1, 100).reshape((10, 10))

array([[0.1       , 0.10909091, 0.11818182, 0.12727273, 0.13636364,
        0.14545455, 0.15454545, 0.16363636, 0.17272727, 0.18181818],
       [0.19090909, 0.2       , 0.20909091, 0.21818182, 0.22727273,
        0.23636364, 0.24545455, 0.25454545, 0.26363636, 0.27272727],
       [0.28181818, 0.29090909, 0.3       , 0.30909091, 0.31818182,
        0.32727273, 0.33636364, 0.34545455, 0.35454545, 0.36363636],
       [0.37272727, 0.38181818, 0.39090909, 0.4       , 0.40909091,
        0.41818182, 0.42727273, 0.43636364, 0.44545455, 0.45454545],
       [0.46363636, 0.47272727, 0.48181818, 0.49090909, 0.5       ,
        0.50909091, 0.51818182, 0.52727273, 0.53636364, 0.54545455],
       [0.55454545, 0.56363636, 0.57272727, 0.58181818, 0.59090909,
        0.6       , 0.60909091, 0.61818182, 0.62727273, 0.63636364],
       [0.64545455, 0.65454545, 0.66363636, 0.67272727, 0.68181818,
        0.69090909, 0.7       , 0.70909091, 0.71818182, 0.72727273],
       [0.73636364, 0.74545455, 0.7545454

#### Создайте массив из 20 линейно удаленных точек от 0 до 1( см linspace):

In [26]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Индексы

В матрице

In [27]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

Напишите код таким образом, чтоб появился вывод на экран

In [32]:
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [34]:
mat[-3:, -4:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [37]:
mat[3, 4]

np.int64(20)

In [38]:
mat[3][4]

np.int64(20)

In [41]:
mat[:3, 1:2]

array([[ 2],
       [ 7],
       [12]])

In [44]:
mat[-5:-2, -4:-3]

array([[ 2],
       [ 7],
       [12]])

In [49]:
mat[4:]

array([[21, 22, 23, 24, 25]])

In [50]:
mat[-1]

array([21, 22, 23, 24, 25])

In [52]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [51]:
mat[-2:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Теперь сделайте следующее

#### Получить сумму всех значений в mat

In [60]:
mat.sum()

np.int64(325)

#### Получить стандартное отклонение значений в mat (пакет Статистика)

In [61]:
np.std(mat)

np.float64(7.211102550927978)

#### Посчитайте сумму всех столбцов в mat

In [62]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])